# This is a basic workflow to help you get started with Actions

name: Auto Update

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 15 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  auto-update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      discussions: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: "${{ secrets.ACCESS_TOKEN }}"

      - name: Checkout to english
        run: git checkout english

      # Add remote english upstream
      - name: Add remote upstream
        run: git remote add upstream https://github.com/microsoft/Web-Dev-For-Beginners.git

      # Fetch upstream
      - name: Fetch upstream
        run: git fetch upstream

      - name: Set main commit sha variables
        run: git rev-parse english | read maincommit

      - name: Set upstream main commit sha variables
        run: git rev-parse upstream/main | read upstreamcommit

      - name: Check version
        shell: bash
        run: |
          if [ $maincommit == $upstreamcommit ]; then
          echo "This repository is already up-to-date"
          else
          echo "This repository is old version. Update from https://github.com/microsoft/Web-Dev-For-Beginners.git"
          fi

      - name: Checkout to english
        run: git checkout english
        
      # Merge upstream/main to main
      - name: Merge branch
        if: ${{ env.maincommit == env.upstreamcommit }}
        run: git merge upstream/main

      - name: GitHub Push
        if: ${{ env.maincommit == env.upstreamcommit }}
        run: git push origin english

      - run: echo "This job's status is ${{ job.status }}."